
name: Benchmark

on:
  push:

env:
  FORCE_COLOR: 1

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        name: Setup Bun
        with:
          bun-version: latest

      - run: bun i
      - run: bun benchmark.ts
